import Head from 'next/head'
import {useQuery} from "react-query";
import {getUser} from "@/components/layout";
import {post} from "@/utils/fetchMiddleware";
import CustomerPortalButton from "@/components/customerPortalButton";
import {TweetArea} from "@/components/tweetArea";
import Link from "next/link";

// const inter = Inter({subsets: ['latin']})

export const makeTweet = (data: any) => {
    return post('twitter/post/', {tweet: data})
}

export default function Home() {
    const {data: userData} = useQuery(['user'], getUser)

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            {/*<Layout>*/}
            <main className={''}>
                <div className={`space-y-4`}>
                    <code>
                        <pre className={``}>{JSON.stringify(userData, undefined, 2)}</pre>
                    </code>
                    <div className={`space-y-4`}>
                        <TweetArea/>
                        <div className={`space-x-4`}>
                            <CustomerPortalButton/>
                            <Link className={`btn`} href={`/subscribe`}>Subscribe</Link>
                        </div>

                    </div>
                </div>
            </main>
            {/*</Layout>*/}
        </>
    )
}
