import {useQuery} from "react-query";
import Head from "next/head";
import {axiosPublic} from "@/utils/axiosPublic";

const getTwitterLink = () => {
    return axiosPublic.get("twitter/get-twitter-login/")
}

export default function Login({}) {
    const {data: twitterLink} = useQuery(["getTwitterLink"], getTwitterLink)

    // TODO: check if user is logged-in, if user is logged in, redirect the user to home page
    const handleLoginWithTwitter = () => {
        window.location = twitterLink?.data
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            {/*<Layout>*/}
            <main className={`h-screen flex justify-center items-center`}>
                <div>
                    <button className={`bg-blue-500 px-8 py-4 rounded-full text-white`}
                            onClick={() => handleLoginWithTwitter()}>
                        Login with Twitter
                    </button>
                </div>
            </main>
            {/*</Layout>*/}
        </>
    )

}
