import {useQuery} from "react-query";
import Head from "next/head";
import {get, getUser} from "@/utils/fetchMiddleware";
import {useEffect} from "react";
import {useRouter} from "next/router";

const getTwitterLink = () => {
    return get("twitter/get-twitter-login/")
}

export default function Login({}) {
    const {data} = useQuery(["getTwitterLink"], getTwitterLink)

    const router = useRouter()

    useEffect(() => {
        getUser.then(user => {
            if (!!user) {
                router.push('/')
            }
        });
    }, [getUser])

    const handleLoginWithTwitter = () => {
        window.location = data
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            {/*<Layout>*/}
            <main className={`h-screen flex justify-center items-center`}>
                <div>
                    <button className={`bg-blue-500 px-8 py-4 rounded-full text-white`}
                            onClick={() => handleLoginWithTwitter()}>
                        Login with Twitter
                    </button>
                </div>
            </main>
            {/*</Layout>*/}
        </>
    )

}
