import {useQuery} from "react-query";
import Head from "next/head";
import {useRouter} from "next/router";
import {axiosPublic} from "@/utils/axiosPublic";
import {getUser} from "@/components/layout";
import {useEffect} from "react";

const getTwitterLink = () => {
    return axiosPublic.get("twitter/get-twitter-login/")
}

export default function Login({}) {
    const {isError, isLoading, data: userData, error, status} = useQuery(['user'], () => getUser())
    const {data: twitterLink} = useQuery(["getTwitterLink"], getTwitterLink)

    const router = useRouter()

    useEffect(() => {
        if (!!userData?.data.pk) {
            router.push('/')
        }
    }, [userData])

    const handleLoginWithTwitter = () => {
        // @ts-ignore
        console.log(data)
        window.location = twitterLink?.data
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            {/*<Layout>*/}
            <main className={`h-screen flex justify-center items-center`}>
                <div>
                    <button className={`bg-blue-500 px-8 py-4 rounded-full text-white`}
                            onClick={() => handleLoginWithTwitter()}>
                        Login with Twitter
                    </button>
                </div>
            </main>
            {/*</Layout>*/}
        </>
    )

}
